### ISSUE TITLE
Using the same names for parameters in BDD steps results in a conflict

### ISSUE THREAD

**Issue by DmitryKorolev-TomTom** [pytest-dev/pytest-bdd#438] opened 2021-08-06 07:30 UTC
If multiple steps are using the same parameter name, the first occurrence will populate the fixture value and that value will be used in all successive occurrences. I will illustrate it on the example:

```
  Scenario Outline: example
    When I apply ABC
    Then the status is <status>
    Examples:
      | status |
      | XYZ    |
```

```
@when(parsers.parse("I apply {status}"))
def apply(status):
    pass

@then(parsers.parse("the status is <status>"))
def check(status):
    assert_that(status, equal_to("XYZ"))
```

My expectation here is that in `then` step value for `status` will be populated from the example table. However, this is not the case as this test fails with:
```
assert_that(status, equal_to("XYZ"))
AssertionError:
Expected: 'XYZ'
     but: was 'ABC'
```

**Comment by jirikuncar** [comment] 2021-08-06 10:14
My understanding is that something around these lines should work for you:

```python
@pytest.fixture
def ctx():
    return {}

@when(parsers.parse("I apply {status}"))
def apply(ctx, status):
    ctx["status"] = status

@then(parsers.parse("the status is <status>"))
def check(ctx, status):
    assert_that(status, equal_to(ctx["status"]))
```

**Comment by elchupanebrej** [comment] 2021-08-10 18:36
Duplicate of #412

**Comment by olegpidsadnyi** [comment] 2022-01-14 09:17
@DmitryKorolev-TomTom is this still a case since the refactoring? Now the scenario renders <status> before matching the step and all steps should use {status} to parse it. Please check with the latest and close the issue if it works.

**Comment by elchupanebrej** [comment] 2022-07-24 00:50
There is a possibility to dissociate usage of step parameters and fixtures: https://github.com/elchupanebrej/pytest-bdd-ng#step-arguments-are-fixtures-as-well

**Comment by youtux** [comment] 2022-07-24 17:48
Closing this as this should have been fixed in the latest versions of pytest-bdd. Please retry with the latest version of pytest-bdd, I will reopen the issue if the problem is still present.

**Closed by youtux** 2022-07-24 17:48 UTC
