### ISSUE TITLE
INTERNALERROR> AttributeError: 'PyLintItem' object has no attribute 'function'

### ISSUE THREAD

**Issue by ajinkyapande** [pytest-dev/pytest-bdd#352] opened 2020-03-19 12:06 UTC
Getting this error when i am running pylint  . Not sure if this issue is from pytest_bdd side or linter side.  Can someone please look into this?

```
$ pytest --pylint -m pylint --pylint-jobs=20 --pylint-error-types=EF
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-5.3.4, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache

plugins: allure-pytest-2.8.12, bdd-3.2.0, dependency-0.5.1, forked-1.1.3, pylint-0.15.1, rerunfailures-9.0, splinter-2.0.1, timeout-1.3.4, xdist-1.31.0
--------------------------------------------------------------------------------
Linting files
......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
--------------------------------------------------------------------------------
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/_pytest/main.py", line 197, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/_pytest/main.py", line 246, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/_pytest/main.py", line 256, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/_pytest/main.py", line 461, in perform_collect
INTERNALERROR>     session=self, config=self.config, items=items
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pytest_bdd/plugin.py", line 106, in pytest_collection_modifyitems
INTERNALERROR>     items.sort(key=item_key)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pytest_bdd/plugin.py", line 104, in item_key
INTERNALERROR>     pytest_bdd_counter = getattr(item.function, '__pytest_bdd_counter__', 0)
INTERNALERROR> AttributeError: 'PyLintItem' object has no attribute 'function'

============================= 52 warnings in 6.17s =============================

**Comment by youtux** [comment] 2020-04-19 14:20
Please make sure you are using the most up-to-date version of pytest-bdd. Version 3.2.1 seems to be solving that issue.

**Comment by youtux** [comment] 2020-04-19 14:21
Duplicate of https://github.com/pytest-dev/pytest-bdd/issues/317

**Closed** 2020-04-21 12:04 UTC
Labels: duplicate, invalid
