### ISSUE TITLE
Issue with parsers.cfparse

### ISSUE THREAD

**Issue by sruthi24** [pytest-dev/pytest-bdd#251] opened 2018-08-06 21:13 UTC
Using parsers.cfparse is giving StepDefinitionNotFoundError

@when(parsers.cfparse('{messages:Number} messages are sent ',
                      extra_types=dict(Number=int)))

@then(parsers.cfparse('{messages:Number} messages are received by the client',
                      extra_types=dict(Number=int)))

Feature file has properly defined steps 

**Issue log:**
argname = 'pytestbdd_when_100 messages are sent '

 def _get_active_fixturedef(self, argname):
 try:
> return self._fixture_defs[argname]
E KeyError: 'pytestbdd_when_100 messages are sent '

/usr/local/lib/python3.6/site-packages/_pytest/fixtures.py:520: KeyError

E pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: When "100 messages are sent "

This issue started from the last two days . Previously not seeing this with parsers.cfparse. Please help on this

**Comment by The-Compiler** [comment] 2018-08-07 04:26
Duplicate of #250

**Closed by The-Compiler** 2018-08-07 04:26 UTC
