### ISSUE TITLE
Does pytest-bdd support pytest-xdist?

### ISSUE THREAD

**Issue by jun-x-nova** [pytest-dev/pytest-bdd#679] opened 2024-03-12 08:05 UTC
Running pytest-bdd (selenium script) in parallel with pytest-xdist does not collect the results in the report.

**Comment by AmirYa412** [comment] 2024-03-12 15:26
I wasn't even able to run the tests with pytest-xdist.
I posted the issue in https://github.com/pytest-dev/pytest-xdist/issues/1038
and pytest-xdist dev responded with:

> Pytest-bdd Lacks a report serialize/deserialize Hook to handle its data
> This is a pytest-bdd issue

Only way I was able to run in parallel is using pytest-parallel, but its very old and seems to be no longer supported.
I think this issue is critical, parallel execution is a basic need.

**Comment by youtux** [comment] 2024-03-13 20:22
Hi, pytest-bdd works with pytest-xdist, we also have a test for it. If it doesn't work for you, please provide a [MCVE](https://en.wikipedia.org/wiki/Minimal_reproducible_example) so that I can debug the issue.

I even tried reproducing the issue installing py3.7,  pytest==7.4.3, pytest-bdd==6.1.1, pytest-xdist==3.5.0, but I don't see any error.

Closing this unless more info is provided.

**Closed by youtux** 2024-03-13 20:22 UTC
